name: nhost_flutter_graphql
description: >
  Provides GraphQL clients to your Flutter application, automatically configured
  to work with Nhost
version: 0.0.0
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-flutter-graphql

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^4.0.0

  # Nhost packages
  nhost_dart_sdk: ^0.6.0
  nhost_flutter_auth: ^0.0.0
  nhost_graphql_adapter: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
