name: nhost_flutter_graphql
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^4.0.0
  nhost_dart_sdk:
    path: ../nhost-dart-sdk
  nhost_flutter_auth:
    path: ../nhost-flutter-auth
  nhost_graphql_adapter:
    path: ../nhost-dart-graphql-adapter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
