name: nhost_graphql_adapter
version: 0.2.0
description: Easily connect to your Nhost GraphQL backend.
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart-graphql-adapter

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  graphql: '>=4.1.0-beta.1 <6.0.0'
  http: ^0.13.0
  meta: ^1.0.0

  # Nhost packages
  nhost_dart_sdk: ^0.0.0

dev_dependencies:
  async: ^2.0.0
  mockito: ^5.0.0
  nock: ^1.0.0
  pedantic: ^1.9.0
  stream_channel: ^2.0.0
  test: ^1.14.4
  web_socket_channel: ^2.0.0
