name: nhost_flutter_auth
description: >
  Provides Nhost authentication state to your Flutter app, making it easy to set
  up protected resources, and react to logins and logouts.
version: 0.3.0+2
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/packages/nhost_flutter_auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.4"

dependencies:
  flutter:
    sdk: flutter

  # Nhost packages
  nhost_sdk: ^0.8.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.9.0
