name: nhost_flutter_auth
description:
version: 1.0.0
homepage: https://nhost.io
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nhost_dart_sdk:
    path: ../nhost-dart-sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
