targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          schema: nhost_ferry_adapter_example|lib/graphql/schema.graphql
          type_overrides:
            timestamptz:
              name: DateTime
            uuid:
              name: String

      gql_build|ast_builder:
        enabled: true

      gql_build|data_builder:
        enabled: true
        options:
          schema: nhost_ferry_adapter_example|lib/graphql/schema.graphql
          type_overrides:
            timestamptz:
              name: DateTime
            uuid:
              name: String

      gql_build|var_builder:
        enabled: true
        options:
          schema: nhost_ferry_adapter_example|lib/graphql/schema.graphql
          type_overrides:
            timestamptz:
              name: DateTime
            uuid:
              name: String

      gql_build|serializer_builder:
        enabled: true
        options:
          schema: nhost_ferry_adapter_example|lib/graphql/schema.graphql
          custom_serializers:
            - import: 'package:nhost_ferry_adapter/postgres_types.dart'
              name: UuidSerializer
            - import: 'package:nhost_ferry_adapter/postgres_types.dart'
              name: TimestamptzSerializer
          type_overrides:
            timestamptz:
              name: DateTime
            uuid:
              name: String

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: nhost_ferry_adapter_example|lib/graphql/schema.graphql
          type_overrides:
            timestamptz:
              name: DateTime
            uuid:
              name: String
