name: nhost_dart_sdk
description:
private: true

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.13.0
  json_annotation: ^3.0.0
  jwt_decoder: ^2.0.0
  meta: ^1.0.0
  path: ^1.0.0
  pedantic: ^1.8.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  test: ^1.6.0
