name: nhost_dart_sdk
description: Nhost authentication and file storage/retrieval APIs for the Dart language
homepage: https://nhost.io
reposity: https://github.com/nhost-dart-sdk
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.13.0
  json_annotation: ^3.0.0
  jwt_decoder: ^2.0.0
  meta: ^1.0.0
  path: ^1.0.0
  pedantic: ^1.8.0

dev_dependencies:
  build_runner: ^1.0.0
  dart_otp: ^1.0.0
  fake_async: ^1.0.0
  json_serializable: ^3.0.0
  nock: ^1.0.0
  test: ^1.6.0
  nhost_graphql_adapter:
    path: ../nhost-dart-graphql-adapter
