name: nhost_dart_sdk
version: 0.0.0
description: Nhost authentication and file storage/retrieval APIs for the Dart language
homepage: https://nhost.io
repository: https://github.com/nhost-nhost-dart-sdk

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.13.0
  http_parser: ^4.0.0
  json_annotation: ^3.0.0
  jwt_decoder: ^2.0.0
  meta: ^1.0.0
  path: ^1.0.0
  pedantic: ^1.8.0

dev_dependencies:
  betamax: ^2.0.0-dev.0
  build_runner: ^1.0.0
  dart_otp: ^1.0.0
  fake_async: ^1.0.0
  json_serializable: ^3.0.0
  nock: ^1.0.0
  test: ^1.6.0
  stack_trace: ^1.0.0

  # Nhost packages
  nhost_graphql_adapter: ^0.0.0
