name: nhost_sdk
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0
  meta: ^1.0.0
  pedantic: ^1.8.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  test: ^1.6.0
