name: nhost_ferry_adapter_example
description: Demonstrates usage of the nhost_ferry_adapter package
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ferry:
  built_value:

  # Nhost packages
  nhost_ferry_adapter:
    path: ../

dev_dependencies:
  build_runner: ^2.0.3
  ferry_generator: ^0.4.2
