name: score-quality
on: push

jobs:
  # Ensure that the package meets a 100% pub.dev score (which impacts the sort
  # order of search results on the package manager site)
  score:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: axel-op/dart-package-analyzer@v3
      # Set an id for the current step, so we can reference it later
      id: analysis
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Require analysis perfection
      env:
        # "analysis" is the id set above
        TOTAL: ${{ steps.analysis.outputs.total }}
        TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        PLATFORMS: ${{ steps.analysis.outputs.platforms }}
        PLATFORMS_MAX: ${{ steps.analysis.outputs.platforms_max }}
      run: |
        PERCENTAGE=$((( $TOTAL - $PLATFORMS ) * 100 / ( $TOTAL_MAX - $PLATFORMS_MAX )))
        if (( $PERCENTAGE < 100 ))
        then
          echo Score to low.
          exit 1
        fi
