name: test
on: push

jobs:
  # Analyzes, checks formatting, and tests the packages
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # We test against several Flutter versions
        flutter_channel: ['stable', 'beta']

    steps:
    - uses: actions/checkout@v2

    # Setup the flutter environment
    - uses: subosito/flutter-action@v1.4.0
      with:
        channel: ${{ matrix.flutter_channel }}

    # Get package dependencies
    - run: pub get

    # Check for any formatting issues in the code
    - run: dart format --set-exit-if-changed .

    # Statically analyze the Dart code for any errors
    - run: dart analyze .

    # Do the same for examples
    - run: dart analyze ./example

    # Run widget tests for our flutter project
    - run: pub run test
